### ISSUE TITLE
GPU Acceleration Problem

### ISSUE THREAD

**Issue by KitsuKatsu333** [solarorb93/BetaSuite#59]
Not sure if this is the correct place to post this, but I've been working on trying to get GPU acceleration to work for a couple days now. I tried several different things. I installed the wrong version of CUDA at first however I went through uninstalling that (and near everything else for that matter) and starting from scratch. My GPU is an MSI GeForce RTX 3060, CPU (if it matters) is an AMD Ryzen 7 5800X. 

(error without the spaces)

2023-03- 0219:08:52.1113512[E:onnxruntime:Default,provider_bridge_ort.cc:1304onnxruntime::TryGetProviderInfo_CUDA]D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106onnxruntime::ProviderLibrary::Get[ONNXRuntimeError]:1:FAIL:LoadLibraryfailedwitherror126""whentryingtoload"C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-03-0219:08:52.1194650[W:onnxruntime:Default,onnxruntime_pybind_state.cc:541onnxruntime::python::CreateExecutionProviderInstance]FailedtocreateCUDAExecutionProvider.Pleasereferencehttps://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirementstoensurealldependenciesaremet.

![errorpic](https://user-images.githubusercontent.com/95542247/222607946-666fcc41-0dff-4b10-a81d-cbdeef67086e.PNG)

**Comment by KitsuKatsu333** [comment]
OK nevermind I think I fixed it. Somehow updating my BIOS worked. Solved

**Comment by eranmp** [comment]
To solve this problem I:
Updated bios
Made sure to install cuda 11.4.4 with Microsoft Visual Studio 2019 ensuring that NVIDIA Nsight was installed during cuda installation.
Made sure to install cudnn v8.2.2.26 (follow the rest of the betasuite readme etc.)
After that, still getting this error, in elevated command prompt typed the following commands:
'pip uninstall onnxruntime-gpu'
'pip install onnxruntime-gpu==1.11'
'pip uninstall numpy'
'pip install numpy==1.26.4'

i have no idea wtf any of this is outside of following bs readme but in short i've surmised that onnxruntime and numpy's newest versions won't work. so downgrading by entering the last four commands may be all you need to do.
